### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by martinvd** [mattallty/Utils-IP-Tools#5]
Hi and thank you for this cool package! I noticed that [this](https://github.com/mattallty/Utils-IP-Tools/commit/601c84d2d0925229add0d8230b0dfbc9eb3c0866) fix is not tagged in a version yet. Could you please create a new tag? Otherwise I have to use the dev version in packagist.

Thanks in advance! :+1:

**Comment by mattallty** [comment]
Hi, no problem, I've created the 1.0.1 tag
